import { Sparkles } from "lucide-react";

import { Card, CardContent, CardHeader, CardTitle } from "../../../components/ui/card";
import { Badge } from "../../../components/ui/badge";

import type { AIThreatAnalysis } from "../types/threatIntelligence";

interface Props {
  analysis: AIThreatAnalysis;
}

export default function AIThreatAnalysisCard({ analysis }: Props) {
  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="flex items-center gap-2">
          <Sparkles className="size-4 text-primary" />
          AI Threat Analysis
        </CardTitle>
        <Badge variant="secondary">{analysis.confidence}% confidence</Badge>
      </CardHeader>

      <CardContent className="space-y-5">
        <div>
          <h4 className="text-sm font-semibold">Executive Summary</h4>
          <p className="mt-1 text-sm text-muted-foreground">{analysis.executiveSummary}</p>
        </div>

        <div>
          <h4 className="text-sm font-semibold">Technical Analysis</h4>
          <p className="mt-1 text-sm text-muted-foreground">{analysis.technicalAnalysis}</p>
        </div>

        {analysis.riskFactors.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold">Risk Factors</h4>
            <ul className="mt-1 list-disc space-y-1 pl-5 text-sm text-muted-foreground">
              {analysis.riskFactors.map((factor, index) => (
                <li key={index}>{factor}</li>
              ))}
            </ul>
          </div>
        )}

        {analysis.recommendations.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold">Recommendations</h4>
            <ul className="mt-1 list-disc space-y-1 pl-5 text-sm text-muted-foreground">
              {analysis.recommendations.map((recommendation, index) => (
                <li key={index}>{recommendation}</li>
              ))}
            </ul>
          </div>
        )}

        <p className="text-xs text-muted-foreground">
          Generated by {analysis.model} on {new Date(analysis.generatedAt).toLocaleString()}
        </p>
      </CardContent>
    </Card>
  );
}
