server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scan
    username: postgres
    password: ak5hu2412
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: "hWmF9sQv6G7xL3nP8aR2kT9yZ4uB1cD5eF7gH9jK2mN5pQ8rS1tV4wX7yZ0aB3cD6"
  expiration: 3600000

virustotal:
  api-key: 63b527b45a9ca168c704b1d3d4169b1e2f1af39a4a03aec3ca90a2ed6fd9e383
  base-url: https://www.virustotal.com/api/v3

urlhaus:
  auth-key: 64644607628b0deb6e1773ed0e3ed8c6fe39ac6d18a904ac
  base-url: https://urlhaus-api.abuse.ch/v1

openphish:
  feed-url: https://raw.githubusercontent.com/openphish/public_feed/refs/heads/main/feed.txt

phishtank:
  app-key: ${PHISHTANK_APP_KEY:}
  base-url: https://checkurl.phishtank.com/checkurl

google-safe-browsing:
  api-key: ${GOOGLE_SAFE_BROWSING_API_KEY:}
  base-url: https://safebrowsing.googleapis.com

abuseipdb:
  api-key: ${ABUSEIPDB_API_KEY:}
  base-url: https://api.abuseipdb.com

openai:
  api-key: ${OPENAI_API_KEY:}
  base-url: https://api.openai.com
  model: gpt-4o-mini