spring:
  application:
    name: auth-service
  jpa:
    show-sql: true

  profiles:
    active: prod

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.transaction: TRACE
    org.springframework.orm.jpa: DEBUG